apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura-dev
    hasuraService: custom
  name: hasura-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura-dev
    spec:
      containers:
      - image: hasura/graphql-engine:v2.37.0
        imagePullPolicy: IfNotPresent
        name: hasura-dev
        envFrom:
        - configMapRef:
            name: dev-config
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources: {}
