apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-dev
  name: hasura-dev
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura-dev
  type: LoadBalancer