apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAMESPACE}-config
  namespace: ${NAMESPACE}
data:
  # ENV
  NAMESPACE: '${NAMESPACE}'
  DOMAIN: '${DOMAIN}'
  # SERVER
  VITE_SERVER_ENDPOINT: 'http://${NAMESPACE}.server.${DOMAIN}'
  SERVER_PORT: '${SERVER_PORT}'
  OPENAI_API_KEY: '${OPENAI_API_KEY}'
  # HASURA
  VITE_HASURA_GQL_ENDPOINT: 'http://${NAMESPACE}.hasura.${DOMAIN}/v1/graphql'
  HASURA_ENDPOINT: 'http://${NAMESPACE}.hasura.${DOMAIN}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_JWT_SECRET: '${HASURA_GRAPHQL_JWT_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  HASURA_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}:${PG_PORT}/${POSTGRES_DB}
  HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}:${PG_PORT}/${POSTGRES_DB}
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DEV_MODE: '${HASURA_GRAPHQL_DEV_MODE}'
  # POSTGRES
  PG_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.${NAMESPACE}:${PG_PORT}/${POSTGRES_DB}'
  PG_HOST: '${PG_HOST}'
  PG_USERNAME: '${PG_USERNAME}'
  POSTGRES_USER: '${POSTGRES_USER}'
  PG_PASSWORD: '${PG_PASSWORD}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  PG_PORT: '${PG_PORT}'
  PG_DATABASE: '${PG_DATABASE}'
  POSTGRES_DB: '${POSTGRES_DB}'
  PG_SSL: '${PG_SSL}'
  # FIREBASE
  VITE_FB_API_KEY: '${VITE_FB_API_KEY}'
  VITE_FB_AUTH_DOMAIN: '${VITE_FB_AUTH_DOMAIN}'
  VITE_FB_PROJECT_ID: '${VITE_FB_PROJECT_ID}'
  VITE_FB_STORAGE_BUCKET: '${VITE_FB_STORAGE_BUCKET}'
  VITE_FB_MESSAGING_SENDER_ID: '${VITE_FB_MESSAGING_SENDER_ID}'
  VITE_FB_APP_ID: '${VITE_FB_APP_ID}'
  FIREBASE_PROJECT_ID_DEV: '${FIREBASE_PROJECT_ID_DEV}'
  FIREBASE_SERVICE_ACCOUNT_JSON_DEV: '${FIREBASE_SERVICE_ACCOUNT_JSON_DEV}'
  # KUBERNETES (Consider storing large config like KUBE_CONFIG in a secret rather than a ConfigMap)
  KUBE_CONFIG: '${KUBE_CONFIG}'